# this is the name of the workflow
name: My first workflow
on:
  # any push will trigger this workflow
- push

jobs:
  #name of the job
  my_first_job:
    # from this point onwards its Ubuntu
    runs-on: ubuntu-latest

    steps:
    - name: get date in Github
      id: get_date_in_github
      run: echo "date in github $(date)" 

    - name: list directory
      id: list_directory
      run: echo "$(ls -l)"

    - name: echo github context
      id: echo_github_context
      run: echo "ref_name ${{github.ref_name}} \n respository ${{github.repository}} \n owner ${{github.repository_owner}}"  

  #another job
  #my_second_job: